import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import MainImage from "@/components/mainImage/MainImage";
import { FormProvider } from "@/components/context/FormProvider";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "FrontEnd Mentor | Multi-step Form",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/favicon-32x32.png" />
      </head>
      <body
        className={`${ubuntu.className} antialiased bg-magnolia flex flex-col`}
      >
        <div className="min-h-screen flex flex-col">
          <MainImage />
          <FormProvider>{children}</FormProvider>
        </div>
      </body>
    </html>
  );
}
